config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'record_pdfs/index'
  get 'report', to: 'items#report'

  resources :items
  delete '/customer_items_destroy_all' => 'items#destroy_all'
  devise_for :customers, controllers: {
    customers: 'customers/customers',
    passwords: 'customers/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/home/about' => 'homes#about'
    get '/home/question' => 'homes#question'
    get '/home/mail' => 'homes#mail'
    get '/company' => 'homes#company'
    get '/terms' => 'homes#terms'
    get '/privacypolicy' => 'homes#privacypolicy'
    resources :item
    resources :customers

    delete 'customers/:id' => 'customers#destroy', as: 'destroy_customer'

    put '/customers/:id/update' => 'customers#update', as: 'customer_update'
    get '/customers/:id/my_page' => 'customers#edit', as: :my_page
    get '/customers/:id' => 'customers#index'
    patch '/customers/withdraw' => 'customers#withdraw'
    get '/customers/change' => 'customers#change'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  get 'admin' => 'homes#top'

  namespace :admin do
    resources :items, only: [:show]
    resources :customers, only: %i[index show update edit] do
      collection do
        get 'search'
      end
    end

    get '/customers_profile' => 'customers#profile', as: :customers_profile
  end
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :admin, optional: true
  has_many :items

  validates :name, presence: true
  validates :kana, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def self.guest
    find_or_create_by!(name: 'ゲスト', kana: 'フリガナ', address: '住所サンプル', phone_number: '08012345678',
                       email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end
  def too_young
    if self.id == 30  #20歳以上の場合
       return "大人です！"
    else  #20歳以下の場合
       return "子供です！"
    end
  end

  # addressを登録した際にgeocoderが緯度、経度のカラムにも自動的に値を入れてくれる
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :set_q, only: %i[profile search]

  def index
    @customer_items = Customer.joins(:items)
    # クエリストリングがあればTimeオブジェクトに変換、ない場合は現在の時刻を取得
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    # 取得した時刻が含まれる月の範囲のデータを取得+N+1のcustomerを追加
    @items = Item.where(date: @month.all_month).order('date ASC').includes(:customer)
    # 出荷量データ
    @customer_data = Customer.joins(:items).where(items: { date: @month.all_month }).group(:name).sum(:count)

    @all_data = Customer.joins(:items)

    gon.customer_data = @customer_data
    # graph_labels = Customer.joins(:items).where(items: { date: @month.all_month }).map(&:name).uniq
    gon.graph = Customer.joins(:items).where(items: { date: @month.all_month }).group(:name).sum(:count)
    gon.graph_counts = gon.graph.values
    gon.graph_labels = gon.graph.keys
    # item.where(name: label, date: @month.all_month).sum(:count)
  end

  def search

    if @q.result === []
      redirect_to admin_customers_profile_path, notice: '該当データが見つかりませんでした。'
    else
      @results = @q.result.find_by(@q.id)
    end

  end

  def profile
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    # クエリストリングがあればTimeオブジェクトに変換、ない場合は現在の時刻を取得
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    # 取得した時刻が含まれる月の範囲のデータを取得
    @items = @customer.items.where(date: @month.all_month).order('date ASC')
    # 円グラフに活用
    @graph_items = Item.where(customer_id: @customer).where(date: @month.all_month).group(:name).order(:date).sum(:count)
  end

  def set_q
    @q = Customer.ransack(params[:q])
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :ensure_normal_customer, only: :destroy
  before_action :ensure_normal_user, only: %i[update destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def ensure_normal_user
    redirect_to root_path, alert: 'ゲストユーザーは削除できません。' if resource.email == 'guest@example.com'
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to customer_path(current_customer), notice: 'ゲストユーザーとしてログインしました。'
  end
end

def new
  @login = Session.new
end

def create
  @login = Session.new(email: params[:session][:email], password: params[:session][:password])
  if @login.save && (@user = User.find_by(email: @login.email)) && @user.authenticate(@login.password)
    redirect_to users_path
  else
    render :new
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
# frozen_string_literal: true

module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="ad-pdf">
  <%= form_with url: record_pdfs_index_path(format: "pdf"),method: 'get'  do |f| %>
    <%= f.label :id, '伝票を作成する場合',required:true %><br>
    <div class=pdf-div>
    ※投稿データのIDを入力してください。
    </div>
    <%= f.number_field :id, placeholder: "例:10"%>
  <% end %>
  <a href="javascript:onPdf()" class="ad-a a-pdf fas fa-download ml-3">伝票を印刷する</a>
</div>


<script>
  function onPdf(){
    var id = document.getElementById('id').value;
    if ( id  == ''){
        alert('IDを入力してください');
        return;
    }
    location.href = "/record_pdfs/index.pdf?id=" + document.getElementById('id').value;
  }
</script>


<form class="border rounded bg-white form-time-table">
  <h1 class="d-flex justify-content-center">全出荷者リスト</h1>
<div class="admin-index">
  <%= link_to "",admin_customers_path(month:@month.prev_month), class: "fas fa-angle-double-left fa-2x" %>
  <strong>
  <%= @month.strftime('%Y/%m') %>
  </strong>
  <%= link_to "",admin_customers_path(month:@month.next_month), class: "fas fa-angle-double-right fa-2x" %>
</div>

<div class="container">
  <!--<div class="vertical-scroll-table">-->
  <table class="table-responsive-sm table-to-export table-bordered" id="fav-table" style="width: -webkit-fill-available;" data-sheet-name="野菜出荷データ">
      <thead>
        <tr class="bg-light text-center">
          <th scope="col">ID</th>
          <th scope="col">名前</th>
          <th scope="col">品目</th>
          <th scope="col">出荷日時</th>
          <th scope="col">出荷先</th>
          <th scope="col">コメント</th>
          <th scope="col">数量</th>
          <th scope="col">規格</th>
          <th scope="col">画像</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr class="text-center">
            <td><%= item.id %></td>
            <% if item.customer.nil? %>
              <td>Guest User</td>
            <% else %>
              <td><%= item.customer.name %></td>
            <% end %>
            <td><%= item.name %></td>
            <td><%= item.date.strftime('%Y/%m/%d')%></td>
            <td><%= item.send_method %></td>
            <td><%= item.comment %></td>
            <td><%= item.count %></td>
            <td><%= item.standard %></td>
            <% if item.customer.nil? %>
              <td><%= image_tag("no-image-icon.jpg") %></td>
            <% else %>
              <td><%= attachment_image_tag(item, :image, :fill, 100, 100, fallback: "no-image-icon.jpg") %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<hr>

<div class="d3">
  <h3>全出荷者　<%= @month.strftime('%Y年%m月') %>分　出荷量分析グラフ</h3>
  <svg width="600" height="240" class="d3" style="background:#f8f8f8";>
</div>
</svg>

<%= javascript_include_tag 'd3' %>

app/views/admin/customers/profile.html.erb
 <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% key = "success" if key == "notice" %>
          toastr['<%= key %>']('<%= value %>');
        <% end %>
      </script>
    <% end %>
<hr>


<h1 class="d-flex justify-content-center">登録生産者一覧</h1>

<div class="search">
<h1>ユーザー検索</h1>
<%= search_form_for @q, url: search_admin_customers_path do |f| %>
  <%= f.label :name_cont, 'ユーザー名' %>
  <%= f.search_field :name_cont , required: true %>
  <%= f.submit '検索' %>
<% end %>
</div>
<div class="container-2">
  <table class= "table-responsive-sm table table-bordered">
   <thead>
      <tr class="bg-light text-center">
        <th scope="col">ID</th>
        <th scope="col">名前</th>
        <th scope="col">フリガナ</th>
        <th scope="col">住所</th>
        <th scope="col">電話番号</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">生産者番号</th>
        <th scope="col" colspan="1">出荷データ</th>
      </tr>
    </thead>
    <tbody>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.name %></td>
        <td><%= customer.kana %></td>
        <td><%= customer.address %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.email %></td>
        <td><%= customer.customer_no %></td>
        <td><%= link_to '詳細', admin_customer_path(customer), class: "customer_#{customer.id} fas fa-poll-h nav-link" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<hr>

<h3>圃場検索</h3>
<div class="map">

  <input type="text" id="address">
  <button id="search">検索</button>
   <div id="target"></div>
</div>


<%= javascript_include_tag 'google.maps' %>

app/views/admin/customers/search.html.erb
<h3>ユーザー検索結果</h3>
 検索ワード:<%= @results.name %>
<hr>

      <h1 class="d-flex justify-content-center"> <%= @results.name %>様 登録データ</h1>
<div class="container">
  <table class= "table table-bordered">
   <thead>
      <tr class="bg-light text-center">
        <th scope="col">ID</th>
        <th scope="col">名前</th>
        <th scope="col">フリガナ</th>
        <th scope="col">住所</th>
        <th scope="col">電話番号</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">生産者番号</th>
        <th scope="col" colspan="1">出荷データ</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @results.id %></td>
        <td><%= @results.name %></td>
        <td><%= @results.kana %></td>
        <td><%= @results.address %></td>
        <td><%= @results.phone_number %></td>
        <td><%= @results.email %></td>
        <td><%= @results.customer_no %></td>
        <td><%#= link_to '詳細', admin_customer_path(@results.id), class: "customer_#{customer.id} fas fa-poll-h fa-2x nav-link" %></td>
      </tr>
    </tbody>
  </table>
</div>
<hr>
</div>

app/views/admin/customers/show.html.erb
 <form class="border rounded bg-white form-time-table">
  <h1 class="d-flex justify-content-center">
    <%= @customer.name %>様
    月別リスト</h1>
<%= link_to "",admin_customer_path(month:@month.prev_month), class: "fas fa-angle-double-left fa-2x" %>
<strong>
<%= @month.strftime('%Y/%m') %>
</strong>
<%= link_to "",admin_customer_path(month:@month.next_month), class: "fas fa-angle-double-right fa-2x" %>
<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr class="bg-light">
        <th scope="col">ID</th>
        <th scope="col">名前</th>
        <th scope="col">品目</th>
        <th scope="col">出荷日時</th>
        <th scope="col">出荷先</th>
        <th scope="col">コメント</th>
        <th scope="col">数量</th>
        <th scope="col">規格</th>
        <th scope="col">画像</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= @customer.name %></td>
          <td><%= item.name %></td>
          <td><%= item.date.strftime('%Y/%m/%d')%></td>
          <td><%= item.send_method %></td>
          <td><%= item.comment %></td>
          <td><%= item.count %></td>
          <td><%= item.standard %></td>
          <td><%= attachment_image_tag(item, :image, :fill, 100, 100, fallback: "no-image-icon.jpg") %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

<hr>
 <div class="search">
<h6>【伝票作成（PDF出力】</h6>
<%= form_with url: record_pdfs_index_path(format: "pdf"),method: 'get'  do |f| %>
  <%= f.label :id, 'PDFの伝票を作成する場合',required:true %>
    ※投稿データのIDを入力してください。<br>
    IDを入力（例：100)
  <%= f.number_field :id %>
<a href="javascript:onPdf()" class="fas fa-download ml-3">対象の伝票を印刷</a>
<% end %>
</div>
<script>
  function onPdf(){
    var id = document.getElementById('id').value;
    if ( id  == ''){
        alert('IDを入力してください');
        return;
    }
    location.href = "/record_pdfs/index.pdf?id=" + document.getElementById('id').value;
  }
</script>

<div>
  <canvas id="stage"></canvas>
</div>

<script>
  //「月別データ」
var mydata = {
  <% items = @graph_items.to_a() %>
  labels: [
    <% items.each do |item| %>
      "<%=item[0]%>",
    <% end %>
  ],
  datasets: [
    {
      label: '数量',
      backgroundColor: ["#c97586","#bbbcde","#7CFC00", "#FF66FF","#FFFF99","#CCFFFF","#66FF99"],
      data: [
        <% items.each do |item| %>
          <%= item[1] %>,
        <% end %>
      ],
    }
  ]
};

//「オプション設定」
var options = {
  title: {
    display: true,
    text: '品目別出荷割合'
  }
};

var canvas = document.getElementById('stage');
var chart = new Chart(canvas, {

  type: 'pie',  //グラフの種類
  data: mydata,  //表示するデータ
  options: options  //オプション設定

});

</script>