config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'record_pdfs/index'
  get 'report', to: 'items#report'

  resources :items
  delete '/customer_items_destroy_all' => 'items#destroy_all'
  devise_for :customers, controllers: {
    customers: 'customers/customers',
    passwords: 'customers/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get '/home/about' => 'homes#about'
    get '/home/question' => 'homes#question'
    get '/home/mail' => 'homes#mail'
    get '/company' => 'homes#company'
    get '/terms' => 'homes#terms'
    get '/privacypolicy' => 'homes#privacypolicy'
    resources :item
    resources :customers

    delete 'customers/:id' => 'customers#destroy', as: 'destroy_customer'

    put '/customers/:id/update' => 'customers#update', as: 'customer_update'
    get '/customers/:id/my_page' => 'customers#edit', as: :my_page
    get '/customers/:id' => 'customers#index'
    patch '/customers/withdraw' => 'customers#withdraw'
    get '/customers/change' => 'customers#change'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  get 'admin' => 'homes#top'

  namespace :admin do
    resources :items, only: [:show]
    resources :customers, only: %i[index show update edit] do
      collection do
        get 'search'
      end
    end

    get '/customers_profile' => 'customers#profile', as: :customers_profile
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Agris(アグリス）|無料で今すぐ使える伝票作成システム・アプリ</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
      <script
        src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=AIzaSyDJ5GOOTLbFLVD8ViuUGcaCcei8E-uTsb0&callback=initMap"
        async
        defer
      ></script>
  </head>

  <body>
    <header>
      <nav class="nav">
      <ul class="header" id= "nav-link">
      <%= link_to root_path, class: "nav-link " do  %>
      <%= image_tag 'agris.logo.png',class: "logo" %>
      <% end %>
      <li><div class="header-fix"></div></li>
       <% if customer_signed_in? %>
              <li class="head-li"><%= link_to " マイページ", my_page_path(current_customer.id), class: "fas fa-user nav-link " %></li>
              <li><%= link_to " 出荷履歴一覧", customer_path(current_customer), class: "fas fa-clipboard-list nav-link " %></li>
              <li><%= link_to " 新規出荷登録", new_item_path, class: "fas fa-plus-square nav-link " %></li>
              <li><%= link_to " 全出荷データ出力", customers_path(format: :csv), class: "fas fa-download  nav-link" %></li>
              <li><%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link ml-3" %></li>

            <% elsif admin_signed_in? %>
              <li><%= link_to " 会員一覧", admin_customers_profile_path, class: "fas fa-users nav-link " %></li>
              <li><%= link_to " 出荷全履歴一覧", admin_customers_path, class: "fas fa-clipboard-list nav-link " %></li>
              <li><%= link_to " 全出荷データCSV出力", admin_customers_path(format: :csv), class: "fas fa-download nav-link " %></li>
              <li><%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link " %></li>

            <% else %>
              <li><%= link_to " 使い方", home_about_path, class: "fas fa-info-circle nav-link " %></li>
              <li><%= link_to " よくある質問と答え", home_question_path, class: "fas fa-info-circle nav-link " %></li>
              <li><%= link_to " 新規登録", new_customer_registration_path, class: "fas fa-user-plus nav-link" %></li>
              <li><%= link_to " ログイン", new_customer_session_path, class: "fas fa-sign-in-alt nav-link " %></li>
              <li><%= link_to " 管理者ログイン", new_admin_session_path, class: "fas fa-user-tie nav-link " %></li>
              <li><%= link_to " ご意見", home_mail_path, class: "fas fa-envelope-square nav-link " %></li>
              </ul>
              </nav>
              <div class="guest">
              <%= link_to " ゲストログイン（閲覧用）", customers_guest_sign_in_path, method: :post, class: "fas fa-chalkboard-teacher nav-link" %>
              <%= link_to " 管理者ゲストログイン（閲覧用）", admins_guest_sign_in_path, method: :post, class: "fas fa-chalkboard-teacher nav-link" %>
              </div>
            <% end %>
    </header>
    <%= yield %>

              <button type="button" id="navbtn">
                <div class="c-hamburger-btn__bars">
              		<div class="c-hamburger-btn__bar"></div>
              		<div class="c-hamburger-btn__bar"></div>
              		<div class="c-hamburger-btn__bar"></div>
              	</div>
              </button>
    <span id="back">
      <a href="#">
        <%= image_tag 'arrow.png', alt: "" %>
      </a>
    </span>
    <footer>
      <section>
        <div class="footer-side-all">
          <%= image_tag 'logo.png',class: "logo" %>
        </div>
        <div class="footer-side">
          <p>Agris（アグリス）は従来の紙でおこなっていた伝票処理を、スマートフォンやPCでおこなうサービス・アプリです。必要なものはスマートフォン１つ。伝票作成等の事務解消にお使いください。</p>
        </div>
      </section>
      <div class="footer-link">
        <%= link_to " 使い方", home_about_path, class: "fas fa-info-circle nav-link-footer " %><br>
        <%= link_to " よくある質問と答え", home_question_path, class: "fas fa-info-circle nav-link-footer " %><br>
        <%= link_to " 新規登録", new_customer_registration_path, class: "fas fa-user-plus nav-link-footer" %><br>
        <%= link_to " ログイン", new_customer_session_path, class: "fas fa-sign-in-alt nav-link-footer " %><br>
        <%= link_to " 管理者ログイン", new_admin_session_path, class: "fas fa-user-tie nav-link-footer " %><br>
      </div>
      <div class="footer-link-2">
        <%= link_to " 運営・開発者", company_path, class: " nav-link-footer " %><br>
        <%= link_to " 利用規約", terms_path, class: " nav-link-footer " %><br>
        <%= link_to " プライバシーポリシー", privacypolicy_path, class: " nav-link-footer" %><br>
        <%= link_to " 不具合報告", home_mail_path, class: " nav-link-footer " %><br>
      </div>
      <div>
      </div>
    </footer>
      <div class="copyright text-center">
       Copyright © Agis Nextinnovation inc. All Rights Reserved.
      </div>

  </body>
</html>